// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1FJTN9jqFUIWW_DLRmZafgKZ3QxyRLKI',
    appId: '1:517067592517:web:618bd16358648fa545242c',
    messagingSenderId: '517067592517',
    projectId: 'reddit-clone-4ee78',
    authDomain: 'reddit-clone-4ee78.firebaseapp.com',
    storageBucket: 'reddit-clone-4ee78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMqOz3ABSfQ97JPZFWkokbhuoIlN_EaU',
    appId: '1:517067592517:android:2d40957f8620c0c445242c',
    messagingSenderId: '517067592517',
    projectId: 'reddit-clone-4ee78',
    storageBucket: 'reddit-clone-4ee78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvvMorn7XMbWKNzvmHsbnO0IRDdERsYUM',
    appId: '1:517067592517:ios:35528c2cac58cddf45242c',
    messagingSenderId: '517067592517',
    projectId: 'reddit-clone-4ee78',
    storageBucket: 'reddit-clone-4ee78.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
